api:
    listen: 8085
cors:
    origins:
        - http://127.0.0.1:3000
        - http://127.0.0.1:8085
jwt:
    email: 19822
    key: ws
smtp:
    host: smtp.qq.com
    password: kefgmv
    port: 465
    username: 19822
