api:
  listen: 8085
cors:
  origins:
    - http://127.0.0.1:3000
    - http://127.0.0.1:8085
    - http://localhost:3000
jwt:
  email: 1982209396@qq.com
  key: Wsr19990902
smtp:
  host: smtp.qq.com
  password: dlbeaalzygvrefjb
  port: 465
  username: 1982209396@qq.com
routes:
  - /reset
  - /add
  - /home
  - /
